---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-ssh-keys

      ssh_keys_authorized_keys:
        - user: root
          src: files/id_rsa.pub

      ssh_keys_known_hosts:
        - name: github.com
          type: ssh-rsa
          key: "AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

      ssh_keys_private_keys:
        - owner: root
          group: root
          src: files/id_rsa_deploy
          dest: /root/.ssh/id_rsa_deploy

      ssh_keys_public_keys:
        - owner: root
          group: root
          src: files/id_rsa_deploy.pub
          dest: /root/.ssh/id_rsa_deploy.pub
