---
- name: Converge
  hosts: all
  roles:
    - role: boutetnico.ssh_keys

      ssh_keys_authorized_keys:
        - user: root
          src: files/id_rsa.pub

      ssh_keys_known_hosts:
        - name: github.com
          type: ssh-rsa
          key: "AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTT\
          vD\P6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCs\
          Or/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcE\
          pEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7\
          GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0w\
          QZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK\
          4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2a\
          B6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="

      ssh_keys_private_keys:
        - owner: root
          group: root
          src: files/id_rsa_deploy
          dest: /root/.ssh/id_rsa_deploy

      ssh_keys_public_keys:
        - owner: root
          group: root
          src: files/id_rsa_deploy.pub
          dest: /root/.ssh/id_rsa_deploy.pub
